### ISSUE TITLE
dual_accel_detect.h not found for kernel 5.13

### ISSUE THREAD

**Issue by sylvainfaivre** [JosiahBull/thinkpad_acpi#3]
Hi, I'm running Ubuntu 21.10 with kernel 5.13, and this file does not exist in thise kernel release : 

```
$ sudo dkms build thinkpad_acpi/1.0

Kernel preparation unnecessary for this kernel.  Skipping...

Running the pre_build script:
Version is *.0, correcting version script
Downloading relevant files from linux git repsoitory...
--2022-07-04 09:27:18--  https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/plain/drivers/platform/x86/thinkpad_acpi.c?h=v5.13
Resolving git.kernel.org (git.kernel.org)... 145.40.68.75, 2604:1380:4601:e00::1
Connecting to git.kernel.org (git.kernel.org)|145.40.68.75|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 296592 (290K) [text/plain]
Saving to: ‘thinkpad_acpi.c’

thinkpad_acpi.c                 100%[=====================================================>] 289,64K  --.-KB/s    in 0,1s    

2022-07-04 09:27:18 (2,31 MB/s) - ‘thinkpad_acpi.c’ saved [296592/296592]

--2022-07-04 09:27:18--  https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/plain/drivers/platform/x86/dual_accel_detect.h?h=v5.13
Resolving git.kernel.org (git.kernel.org)... 145.40.68.75, 2604:1380:4601:e00::1
Connecting to git.kernel.org (git.kernel.org)|145.40.68.75|:443... connected.
HTTP request sent, awaiting response... 404 Not found
2022-07-04 09:27:18 ERROR 404: Not found.

Failed to download dual_accel_detect.h

Building module:
cleaning build area...
make -j8 KERNELRELEASE=5.13.0-52-generic -C /lib/modules/5.13.0-52-generic/build M=/var/lib/dkms/thinkpad_acpi/1.0/build.....
Signing module:
 - /var/lib/dkms/thinkpad_acpi/1.0/5.13.0-52-generic/x86_64/module/thinkpad_acpi.ko
Secure Boot not enabled on this system.
cleaning build area...

DKMS: build completed.
```

I experienced some problems while trying to upgrade to Ubuntu 22.04, so I'd like to stay with 21.10 for a few months.

Is there any hope for me ?

**Comment by JosiahBull** [comment]
Hiya, it seems that `dual_accel_detect.h` was only added in kernel 5.14. I took a quick look and `thinhkpad_acpi` should compile without it in this version. I'll modify the script to not attempt download of `dual_accel_detect.h` in kernel versions 5.13 and older, and then you should be good to go. :+1:

`dual_accel_detect.h` is only needed for devices such as the 2 in 1 yoga, to improve detection of which fold orientation they're in, and it doesn't have any bearing on the custom module from working.

In fact, it looks like the lapmode sensor support only got added to the kernel in `v5.9` so I think I'll disable the build script from running on versions before that as it's unneeded.

I'll make a commit referencing this later today and let you know when to give it a try! :)

Thanks for the bug report!

**Comment by sylvainfaivre** [comment]
Well I followed all the steps to install the module, no other errors, but it does not seem to work. Lap mode is still enabled.

```
# sudo modinfo thinkpad_acpi
filename:       /lib/modules/5.13.0-52-generic/kernel/drivers/platform/x86/thinkpad_acpi.ko
license:        GPL
version:        0.26
description:    ThinkPad ACPI Extras
author:         Henrique de Moraes Holschuh <hmh@hmh.eng.br>
author:         Borislav Deianov <borislav@users.sf.net>
alias:          dmi:bvnIBM:bvrI[MU]ET??WW*
alias:          tpacpi
srcversion:     C3FDE9ED06EEB2918743F79
alias:          acpi*:LEN0268:*
alias:          acpi*:LEN0068:*
alias:          acpi*:IBM0068:*
depends:        snd,platform_profile,video,ledtrig-audio,nvram
retpoline:      Y
intree:         Y
name:           thinkpad_acpi
vermagic:       5.13.0-52-generic SMP mod_unload modversions 
sig_id:         PKCS#7
signer:         Build time autogenerated kernel key
sig_key:        0B:50:2C:B4:48:5F:0A:94:52:4C:49:93:4D:0E:1E:ED:02:F0:A3:71
sig_hashalgo:   sha512
[snip]
```

**Comment by JosiahBull** [comment]
> Well I followed all the steps to install the module, no other errors, but it does not seem to work. Lap mode is still enabled.
> 
> ```
> # sudo modinfo thinkpad_acpi
> filename:       /lib/modules/5.13.0-52-generic/kernel/drivers/platform/x86/thinkpad_acpi.ko
> license:        GPL
> version:        0.26
> description:    ThinkPad ACPI Extras
> author:         Henrique de Moraes Holschuh <hmh@hmh.eng.br>
> author:         Borislav Deianov <borislav@users.sf.net>
> alias:          dmi:bvnIBM:bvrI[MU]ET??WW*
> alias:          tpacpi
> srcversion:     C3FDE9ED06EEB2918743F79
> alias:          acpi*:LEN0268:*
> alias:          acpi*:LEN0068:*
> alias:          acpi*:IBM0068:*
> depends:        snd,platform_profile,video,ledtrig-audio,nvram
> retpoline:      Y
> intree:         Y
> name:           thinkpad_acpi
> vermagic:       5.13.0-52-generic SMP mod_unload modversions 
> sig_id:         PKCS#7
> signer:         Build time autogenerated kernel key
> sig_key:        0B:50:2C:B4:48:5F:0A:94:52:4C:49:93:4D:0E:1E:ED:02:F0:A3:71
> sig_hashalgo:   sha512
> [snip]
> ```

Oop, I can see from `version: 0.26` that the modifications weren't applied to your module. I'd recommend you follow uninstall steps and try again with the latest version, I've made some changes which should resolve this issue.

**Comment by JosiahBull** [comment]
Closing as assumed fix, feel free to reopen if this issue is still present.

**Comment by sylvainfaivre** [comment]
Working on my setup (Ubuntu 21.10) with the latest commits, thanks !
