### ISSUE TITLE
wrong systemtap syntax

### ISSUE THREAD

**Issue by sylvainfaivre** [JosiahBull/thinkpad_acpi#4]
I tried the systemtap script and got a syntax error :

```
$ cat lap.stp 
#! /usr/bin/env stap

# This is a guess for possible syntax, I provide no guarantees.
probe module("thinkpad_acpi").function("lapsensor_get").return {
    *present = 1;
    *state = 1;
}

$ sudo stap -g lap.stp 
parse error: expected literal string or number
        saw: operator '*' at lap.stp:5:5
     source:     *present = 1;
                 ^

1 parse error.
Pass 1: parse failed.  [man error::pass1]
Tip: /usr/share/doc/systemtap/README.Debian should help you get started.
```

I scrolled through the systemtap language reference and could not find a syntax using an asterisk. Sorry I could not point to a fix, just letting you know about this.

**Comment by sylvainfaivre** [comment]
I laso tried removing the asterisks, and it seems to trigger another error : 

```
$ cat lap.stp 
#! /usr/bin/env stap

# This is a guess for possible syntax, I provide no guarantees.
probe module("thinkpad_acpi").function("lapsensor_get").return {
    present = 1;
    state = 1;
}

$ sudo stap -g lap.stp 
WARNING: cannot probe .return of 1 inlined functions  lapsensor_get
semantic error: while resolving probe point: identifier 'module' at lap.stp:4:7
        source: probe module("thinkpad_acpi").function("lapsensor_get").return {
                      ^

semantic error: while resolving probe point: identifier 'module' at :4:7
        source: probe module("thinkpad_acpi").function("lapsensor_get").return {
                      ^

semantic error: no match (similar functions: lapsensor_get, palmsensor_get, lapsensor_refresh, proxsensor_exit, lcdshadow_set)

Pass 2: analysis failed.  [man error::pass2]
Tip: /usr/share/doc/systemtap/README.Debian should help you get started.
```

**Comment by JosiahBull** [comment]
I added as a note to the repo for those looking to explore other options, but I don't really have much experience with systemtap - nor the inclination to learn as the main method works for most people.

If you'd like to work on this issue though, feel free to reopen this issue w/ a PR and I'd be happy to merge it. :+1:

**Comment by drishal** [comment]
@sylvainfaivre apologies for pinging you, but could you find the correct syntax for systemtap? (i.e to disable lap detection on my thinkpad)

**Comment by sylvainfaivre** [comment]
@drishal sorry I cannot help you, I didn't look further into systemtap. More recent Gnome and KDE releases automatically turn the power profile back to performance mode after the laptop has stopped moving, so this "lap mode" doesn't really bother me any more.

**Comment by drishal** [comment]
> @drishal sorry I cannot help you, I didn't look further into systemtap. More recent Gnome and KDE releases automatically turn the power profile back to performance mode after the laptop has stopped moving, so this "lap mode" doesn't really bother me any more.

Oh ok I eventually realised in my case powerprofilectl had somehow got "stuck" in lap mode, restarting the service fixed it
